replicaCount: 1
applicationName: aksworkshop

image:
  repository: order
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

resources:
  requests:
    cpu: "200m"
  limits:
    cpu: "400m"

nodeSelector: {}

tolerations: []

affinity: {}

env:
  values:
    - name: PATH_BASE
      value: /order-api

keyVault:
  secrets: orderconstr
  secretsTypes: secret
