replicaCount: 1
applicationName: aksworkshop

image:
  repository: basket
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: acr-loginpwd

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

nodeSelector:
  kubernetes.io/role: agent
  beta.kubernetes.io/os: linux
  type: virtual-kubelet

tolerations:
- key: virtual-kubelet.io/provider
  operator: Exists
- key: azure.com/aci
  effect: NoSchedule

affinity: {}

env:
  values:
    - name: PATH_BASE
      value: /basket-api
  secretmap:
    - name: constr

