replicaCount: 1
applicationName: aksworkshop

image:
  repository: basket
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

affinity: {}

env:
  values:
    - name: PATH_BASE
      value: /basket-api
  secretmap:
    - name: constr

keyVault:
  secrets: basketconstr
  secretsTypes: secret

