apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: default
  environment: prod
  app: aksworksop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: not@used.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}