pool:
  vmImage: 'ubuntu-16.04'
variables:
    azureContainerRegistry: testeduttacr
    azureSubscriptionEndpoint: aksworkshop-tt
steps:
- task: DockerCompose@0
  displayName: Compose build
  inputs:
    action: Build services  
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: src/docker-compose.yml
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)
- task: DockerCompose@0
  displayName: Compose push
  inputs:
    action: Push services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: src/docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)

