pool:
  vmImage: 'ubuntu-16.04'
variables:
    azureContainerRegistry: testeduttacr.azurecr.io
    azureSubscriptionEndpoint: aksworkshop-tt
steps:
- task: DockerCompose@0
  displayName: Compose build
  inputs:
    action: Build services  
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: src/docker-compose.yml
    qualifyImageNames: true
    projectName: ""
    additionalImageTags: $(Build.BuildId)
- task: DockerCompose@0
  displayName: Compose push
  inputs:
    action: Push services
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: src/docker-compose.yml
    projectName: ""
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)
- task: CopyFiles@2
  inputs:
    sourceFolder: /scripts    
    targetFolder: $(Build.ArtifactStagingDirectory)/scripts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/scripts
    artifactName: scripts
