replicaCount: 1
applicationName: aksworkshop

image:
  repository: catalog
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  secretmap:
    - name: constr
  values:
    - name: PATH_BASE
      value: /catalog-api
